# Generated by Django 4.2.4 on 2023-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('user_mobile', models.CharField(default='', max_length=10)),
                ('user_uuid', models.CharField(default='', max_length=255)),
                ('isVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(default='', max_length=254, unique=True)),
                ('primary_whatsapp', models.CharField(default='', max_length=10)),
                ('primary_mobile', models.CharField(default='', max_length=10, unique=True)),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('designation', models.CharField(default='', max_length=10)),
                ('full_name', models.CharField(default='', max_length=52)),
                ('institute_name', models.CharField(default='', max_length=100)),
                ('interest', models.CharField(default='', max_length=20)),
                ('other_interest', models.CharField(default='Null', max_length=50)),
                ('country', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=80)),
                ('pin_code', models.CharField(default='', max_length=6)),
                ('district', models.CharField(default='', max_length=80)),
                ('dob', models.DateField(default='')),
                ('membership_fee', models.CharField(default='1000 individual', max_length=30)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
    ]
