# Generated by Django 4.2.4 on 2023-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibhaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accept_terms',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
