# Generated by Django 4.2.4 on 2023-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibhaApp', '0002_registration_accept_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='primary_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
