# Generated by Django 4.2.4 on 2023-08-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibhaApp', '0003_alter_registration_primary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_verification',
            name='user_otp',
            field=models.CharField(default='', max_length=4),
        ),
    ]
