# Generated by Django 4.2.4 on 2023-08-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibhaApp', '0004_email_verification_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Customer Phone Number')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(default='PENDING', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, verbose_name='Signature ID')),
            ],
        ),
    ]
